<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-40I021D" failures="1" tests="5" name="Test12" time="31.07" errors="0" timestamp="2022-09-23T17:56:15 IST">
  <testcase classname="test.TestNGClass2TestCases" name="test1verifyReturnToMessenger" time="3.181">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at test.TestNGClass2TestCases.test1verifyReturnToMessenger(TestNGClass2TestCases.java:68)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- test1verifyReturnToMessenger -->
  <testcase classname="test.TestNGClass2TestCases" name="test2verifyVisitToOurHelpCenter1" time="0.0">
    <skipped/>
  </testcase> <!-- test2verifyVisitToOurHelpCenter1 -->
  <testcase classname="test.TestNGClass2TestCases" name="test3verifyVisitToOurHelpCenter" time="0.0">
    <skipped/>
  </testcase> <!-- test3verifyVisitToOurHelpCenter -->
  <testcase classname="test.TestNGClass2" name="verifyReturnToMessenger" time="1.991"/>
  <testcase classname="test.TestNGClass2" name="verifyVisitToOurHelpCenter" time="1.962"/>
</testsuite> <!-- Test12 -->
