<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-40I021D" failures="1" tests="3" name="dummy3" time="14.997" errors="0" timestamp="2022-09-23T17:55:01 IST">
  <testcase classname="test.TestNGClass2TestCases" name="test1verifyReturnToMessenger" time="2.709">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at test.TestNGClass2TestCases.test1verifyReturnToMessenger(TestNGClass2TestCases.java:68)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- test1verifyReturnToMessenger -->
  <testcase classname="test.TestNGClass2TestCases" name="test2verifyVisitToOurHelpCenter1" time="0.001">
    <skipped/>
  </testcase> <!-- test2verifyVisitToOurHelpCenter1 -->
  <testcase classname="test.TestNGClass2TestCases" name="test3verifyVisitToOurHelpCenter" time="0.0">
    <skipped/>
  </testcase> <!-- test3verifyVisitToOurHelpCenter -->
</testsuite> <!-- dummy3 -->
