<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-40I021D" failures="1" tests="5" name="Test" time="32.192" errors="0" timestamp="2022-09-23T18:02:18 IST">
  <testcase classname="test.TestNGClass2Copy" name="test1verifyReturnToMessenger" time="3.052">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at test.TestNGClass2Copy.test1verifyReturnToMessenger(TestNGClass2Copy.java:68)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- test1verifyReturnToMessenger -->
  <testcase classname="test.TestNGClass2Copy" name="test2verifyVisitToOurHelpCenter1" time="0.0">
    <skipped/>
  </testcase> <!-- test2verifyVisitToOurHelpCenter1 -->
  <testcase classname="test.TestNGClass2Copy" name="test3verifyVisitToOurHelpCenter" time="0.0">
    <skipped/>
  </testcase> <!-- test3verifyVisitToOurHelpCenter -->
  <testcase classname="test.TestNGClass2" name="verifyReturnToMessenger" time="2.817"/>
  <testcase classname="test.TestNGClass2" name="verifyVisitToOurHelpCenter" time="1.21"/>
</testsuite> <!-- Test -->
